package org.example.exception;

class TryWithoutCatchMain {

    public static void main(String args[])
    {
        try
        {
            System.out.println("Executing try block");
        }
        finally
        {
            System.out.println("Executing finally block");
        }
    }
}


